import { KanbanBoardState } from "./types"

const mockTasks: KanbanBoardState["tasks"] = {
  "task-1": {
    id: "task-1",
    title: "Prepare steel coil PO batch",
    description: "Validate required quantities, UOM conversions, and delivery windows before submitting.",
    assignees: ["AM", "RK"],
    progress: 10,
    priority: "High",
    attachmentsCount: 2,
    commentsCount: 4,
  },
  "task-2": {
    id: "task-2",
    title: "Review polymer additives pricing",
    description: "Cross-check vendor quotes and align with approved budget thresholds for Q1.",
    assignees: ["LT", "MN"],
    progress: 0,
    priority: "Medium",
    attachmentsCount: 1,
    commentsCount: 1,
  },
  "task-3": {
    id: "task-3",
    title: "Submit lubrication oil replenishment",
    description: "Confirm stock levels with warehouse and push PO to approval workflow.",
    assignees: ["KA", "HS"],
    progress: 40,
    priority: "High",
    attachmentsCount: 2,
    commentsCount: 6,
  },
  "task-4": {
    id: "task-4",
    title: "Raise emergency gasket order",
    description: "Fast-track request due to maintenance outage and track expedited delivery.",
    assignees: ["JT", "PB"],
    progress: 55,
    priority: "Medium",
    attachmentsCount: 3,
    commentsCount: 2,
  },
  "task-5": {
    id: "task-5",
    title: "Approve catalyst refill invoice",
    description: "Reconcile invoice against the goods receipt and mark as finance-cleared.",
    assignees: ["EC", "GR"],
    progress: 100,
    priority: "High",
    attachmentsCount: 2,
    commentsCount: 4,
  },
  "task-6": {
    id: "task-6",
    title: "Approve compressor spare parts PO",
    description: "Verify technical compliance checklist and release for vendor fulfillment.",
    assignees: ["HL", "BM"],
    progress: 100,
    priority: "Medium",
    attachmentsCount: 1,
    commentsCount: 2,
  },
  "task-7": {
    id: "task-7",
    title: "Reject duplicate solvent request",
    description: "Duplicate request detected; notify requester and link to existing order.",
    assignees: ["RW", "CN"],
    progress: 100,
    priority: "Low",
    attachmentsCount: 1,
    commentsCount: 3,
  },
  "task-8": {
    id: "task-8",
    title: "Reject non-compliant supplier quote",
    description: "Missing compliance certificate and expired insurance documents.",
    assignees: ["VP", "DS"],
    progress: 100,
    priority: "Medium",
    attachmentsCount: 2,
    commentsCount: 5,
  },
  "task-9": {
    id: "task-9",
    title: "Fulfill bulk packing materials order",
    description: "Goods received and quality-checked. Close PO after GRN confirmation.",
    assignees: ["AL", "NT"],
    progress: 100,
    priority: "High",
    attachmentsCount: 4,
    commentsCount: 7,
  },
  "task-10": {
    id: "task-10",
    title: "Fulfill pallet replacement request",
    description: "Updated inventory in ERP and shared proof of delivery with operations.",
    assignees: ["IM", "QF"],
    progress: 100,
    priority: "Low",
    attachmentsCount: 2,
    commentsCount: 2,
  },
}

export const initialKanbanBoard: KanbanBoardState = {
  tasks: mockTasks,
  columns: {
    draft: {
      id: "draft",
      title: "Draft",
      taskIds: ["task-1", "task-2"],
    },
    submitted: {
      id: "submitted",
      title: "Submitted",
      taskIds: ["task-3", "task-4"],
    },
    approved: {
      id: "approved",
      title: "Approved",
      taskIds: ["task-5", "task-6"],
    },
    rejected: {
      id: "rejected",
      title: "Rejected",
      taskIds: ["task-7", "task-8"],
    },
    fulfilled: {
      id: "fulfilled",
      title: "Fulfilled",
      taskIds: ["task-9", "task-10"],
    },
  },
  columnOrder: ["draft", "submitted", "approved", "rejected", "fulfilled"],
}
